use_parts:
    # 句点とは「。」「！」「？」「!?」の四種類を指す
    # 読点は「、」となり三点は「...」となる。
    # on にした品詞をデータ紐づけに用いる
    # on か off を記述する
    noun_main       : on    # 一般/固有名詞/サ変接続/形容動詞語幹
    pronoun         : off   # 代名詞
    noun_sub        : off   # その他の名詞
    verb_main       : off   # 自立動詞
    verb_sub        : off   # 非自立動詞
    adjective_main  : off   # 自立形容詞
    adjective_sub   : off   # 非自立形容詞
    adverb          : off   # 副詞
    particle        : off   # 助詞
    auxiliary_verb  : off   # 助動詞
    conjunction     : off   # 接続詞
    prefix          : off   # 接頭詞
    filler          : off   # フィラー
    impression_verb : off   # 感動詞
    pre_noun        : off   # 連体詞
    three_dots      : off   # 三点
    phrase_point    : off   # 句点
    reading_point   : off   # 読点
    others          : off   # その他

link_min: 20 # 紐づけられるWikipedia文が最低この数存在するTwitter文を採用する
